import assert from 'node:assert/strict';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';
import { compileIndex, validateManifest, validateRegistry } from '../src/registry.mjs';
import { validateInventory } from '../src/inventory.mjs';
import { OPENCLAW_SOURCE_FIELDS, buildOpenClawSummary, shardOpenClawIndex } from '../src/openclaw.mjs';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

test('native registry validates', async () => { const { skills, errors } = await validateRegistry(root); assert.equal(errors.length, 0, errors.join('\n')); assert.ok(skills.length >= 10); });
test('compiled index is deterministic and content addressed', async () => { const { skills } = await validateRegistry(root); const a = compileIndex(skills); const b = compileIndex(skills); assert.deepEqual(a,b); assert.match(a.registry_hash,/^[a-f0-9]{64}$/); assert.equal(a.count, skills.length); });
test('adapter skills require explicit binding', () => { const x={schema_version:'1.0',id:'x-001',slug:'x',name:'X',version:'1.0.0',category:'x',description:'x',status:'defined',priority:1,routing:{trigger:'x',boundary:'x',invoke_conditions:[],block_conditions:[],fallback_chain:[],tags:[]},execution:{kind:'adapter',binding:null},contracts:{inputs:[],outputs:[]},policy:{cost_class:'low',latency_class:'fast',requires_auth:false,requires_freshness:false,safe_for_parallel:true,stateful:false,logs_required:false},compatibility:{skill_hub:'x',sophie_x:'x',openclaw:'x'}}; assert.ok(validateManifest(x).some((e)=>e.includes('requires binding'))); });
test('archaeology inventory preserves internal candidates and external OpenClaw index', async () => { const r=await validateInventory(root); assert.equal(r.errors.length,0,r.errors.join('\n')); assert.equal(r.history.count,35); assert.equal(r.delta.count,28); assert.equal(r.external.openclaw.index.count,65); assert.equal(r.external.openclaw.summary.native_promotion_count,0); });
test('OpenClaw discovery index normalizes deterministically', async () => { const r=await validateInventory(root); assert.deepEqual(shardOpenClawIndex(r.external.openclaw.index),r.external.openclaw.index_shards); assert.deepEqual(buildOpenClawSummary(r.external.openclaw.index),r.external.openclaw.summary); assert.equal(r.external.openclaw.schema.fields.length,OPENCLAW_SOURCE_FIELDS.length); });
test('OpenClaw inventory remains external to native skill registry', async () => { const {skills}=await validateRegistry(root); assert.equal(skills.some((s)=>s.manifest.id.startsWith('OC-')),false); assert.equal(skills.some((s)=>s.rel.includes('/openclaw/')),false); const r=await validateInventory(root); assert.equal(r.external.openclaw.index.authority,'reference-only'); assert.equal(r.external.openclaw.summary.architecture_policy,'external-reference-only'); });
test('OpenClaw inventory retains governance and review status', async () => { const r=await validateInventory(root); const p=r.external.openclaw.index.projects; assert.equal(p.every((x)=>x.review_status==='Tentative — user review required'),true); assert.equal(p.filter((x)=>x.security_review_required==='Mandatory').length,4); assert.equal(p.find((x)=>x.ecosystem_id==='OC-026')?.project,'agent-skills'); });
test('project-specific profiles stay outside native skill packages', async () => { const {skills}=await validateRegistry(root); for(const s of skills) assert.notEqual(s.manifest.provenance?.project_scope,'project-specific'); const p=await fs.readdir(path.join(root,'profiles','project-specific')); assert.ok(p.length>=4); });
